// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrmmqjmmbelwpojntlmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpybW1xam1tYmVsd3Bvam50bG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDMxMzcsImV4cCI6MjA3MjM3OTEzN30.ZIZkQuTgfcVuDxTH3kepNZt-bN14xNZtrZhhVNyi1WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});